DELIMITER $$
CREATE EVENT `ev_empty_verified_table` 
ON SCHEDULE EVERY 1 DAY
    STARTS (TIMESTAMP(CURRENT_DATE) + INTERVAL 1 DAY)
DO 
  BEGIN 
    TRUNCATE TABLE verified;
    TRUNCATE TABLE users_codes;
  END$$
