module.exports = {
  GetUserSubscribePackages: '/api/user/subscription/packages',
  GetUserSubscribePackageFeatures: '/api/user/subscription/package/:idPackage/features',
  GetUserFaqs: '/api/user/faqs',
  GetUserAboutus: '/api/user/aboutus',
  GetUserCategories: '/api/user/categories',
  GetUserBrands: '/api/user/brands',
  GetUserProducts: '/api/user/products',
  GetUserContactInfo: '/api/user/contact-info',
  GetUserPrivacyPolicy: '/api/user/privacy-policy',
  GetUserTerms: '/api/user/terms',
  GetUserOffers: '/api/user/offers',
  GetUserPayments: '/api/user/payments',
  GetUserSubscribes: '/api/user/subscription/user-subscriptions',
  GetUserTenders: '/api/user/tenders',
  GetUserTendersB2B: '/api/user/tenders/B2B',
  GetUserCares: '/api/user/cares',
  GetUserSettings: '/api/user/settings',
  GetUserProfileInfo: '/api/user/profile/info',
  

  
  PostUserBrand: '/api/user/brand',
  PostUserCategory: '/api/user/category',
  PostUserProduct: '/api/user/product',
  PostUserOffer: '/api/user/offer',
  PostUserAcceptOffer: '/api/user/offer/accept',
  PostUserSubscribe: '/api/user/subscription/subscribe',
  PostUserTender: '/api/user/tender',
  PostUserTenderUpdate: '/api/user/tender/update',
  PostUserUpdateProfile: '/api/user/profile/update',
  PostUserCare: '/api/user/care',
  PostUserCaresReset: '/api/user/cares/reset',
  PostUserIssueReport: '/api/user/issue-report',

  DeleteUserOffer: '/api/user/offer',
  DeleteUserTender: '/api/user/tender',
  DeleteUserCare: '/api/user/care',
}