module.exports = {
  GetUserSubscribePackages: '/api/user/subscription/packages',
  GetUserSubscribePackageFeatures: '/api/user/subscription/package/:idPackage/features',
  GetUserFaqs: '/api/user/faqs',
  GetUserAboutus: '/api/user/aboutus',
  GetUserCategories: '/api/user/categories',
  GetUserBrands: '/api/user/brands',
  GetUserProducts: '/api/user/products',
  GetUserContactInfo: '/api/user/contact-info',
  GetUserOffers: '/api/user/offers',
  GetUserPayments: '/api/user/payments',
  GetUserSubscribes: '/api/user/subscription/user-subscriptions',
  GetUserTenders: '/api/user/tenders',
  GetUserTendersB2B: '/api/user/tenders/B2B',
  GetUserCares: '/api/user/cares',
  GetUserSettings: '/api/user/settings',
  GetUserProfileInfo: '/api/user/profile/info',
  GetUserTenderContacts: '/api/user/tender/contacts',
  GetUserTrash: '/api/user/trash',
  GetUserSeen: '/api/user/seen',

  
  PostUserBrand: '/api/user/brand',
  PostUserCategory: '/api/user/category',
  PostUserProduct: '/api/user/product',
  PostUserOffer: '/api/user/offer',
  PostUserAcceptOffer: '/api/user/offer/accept',
  PostUserExecuteOffer: '/api/user/offer/execute',
  PostUserSubscribe: '/api/user/subscription/subscribe',
  PostUserTender: '/api/user/tender',
  PostUserTenderUpdate: '/api/user/tender/update',
  PostUserUpdateProfile: '/api/user/profile/update',
  PostUserCare: '/api/user/care',
  PostUserCaresReset: '/api/user/cares/reset',
  PostUserIssueReport: '/api/user/issue-report',
  PostUserReqEPay: '/api/user/e-pay',
  PostUserTrash: '/api/user/trash',
  PostUserSeen: '/api/user/seen',
  
  DeleteUserOffer: '/api/user/offer',
  DeleteUserTender: '/api/user/tender',
  DeleteUserCare: '/api/user/care',
  DeleteUserTrash: '/api/user/trash',
}