module.exports = {
  GetUserSubscribePackages: '/api/user/subscription/packages',
  GetUserSubscribePackageFeatures: '/api/user/subscription/package/:idPackage/features',
  GetUserFaqs: '/api/user/faqs',
  GetUserAboutus: '/api/user/aboutus',
  GetUserCategories: '/api/user/categories',
  GetUserBrands: '/api/user/brands',
  GetUserProducts: '/api/user/products',
  GetUserContactInfo: '/api/user/contact-info',
  GetUserPrivacyPolicy: '/api/user/privacy-policy',
  GetUserTerms: '/api/user/terms',
  GetUserOffers: '/api/user/offers',
  GetUserPayments: '/api/user/payments',
  GetUserSubscribes: '/api/user/subscription/user-subscriptions',
  GetUserTenders: '/api/user/tenders',
  GetUserCares: '/api/user/cares',
}