module.exports = {
    ERR_INVALID_ARGUMENT: 'InvalidArgument',
    ERR_INVALID_USER_CODE: 'InvalidUserCode',
    ERR_NOT_EXISTS_USER_NAME: 'NotExistsUser',
    ERR_ACCESS_DENIED: 'AccessDenied',
    ERR_DUPLICATE_USER: 'DuplicateUser',
    ERR_INVALID_USER_NAME: 'InvalidUserName',
    ERR_INVALID_LOGIN: 'InvalidLogin',
    ERR_INVALID_EMAIL: 'InvalidEmail',
    ERR_INVALID_MOBILE: 'InvalidMobile',
    ERR_INVALID_PASSWORD: 'InvalidPassword',
    ERR_INVALID_FIRSTNAME: "InvalidFirstname",
    ERR_INVALID_LASTNAME: "InvalidLastname",
    ERR_INVALID_NAME: "InvalidName",
    ERR_UNKNOWN: 'UnknownError',
    ERR_INACTIVE_ACCOUNT: 'InactiveAccount',
    ERR_UN_ACCEPTED_ACCOUNT: 'UnAcceptedAccount',
    ERR_UN_VERIFIED_MAIL_MOBILE: 'UnVerifiedMailMobile',
    ERR_UN_VERIFIED_MAIL: 'UnVerifiedMail',
    ERR_UN_VERIFIED_MOBILE: 'UnVerifiedMobile',
    ERR_UN_VERIFIED_LOGIN_NAME: 'UnVerifiedLoginName',
    ERR_CAN_NOT_DELETE_USED_ENTITY: 'CanNotDeleteUsedEntity',

    ERR_INVLID_PROMOTION: 'InvalidPromotion',
    ERR_INVALID_SUBSCRIBE_PACKGE: 'InvalidSubscribePackage',
    ERR_TENDERS_CNT_MONTHLY_EXCEED: 'TENDERS_CNT_MONTHLY_EXCEED',
    ERR_TENDERS_CNT_DAYLY_EXCEED: 'TENDERS_CNT_DAYLY_EXCEED',
    ERR_ACCEPT_OFFERS_CNT_EXCEED: 'ACCEPT_OFFERS_CNT_EXCEED',
    ERR_MAX_OFFER_TIME_EXCEED: 'MaxOfferTimeExceed',
    ERR_FINAL_STATUS: 'FinalStatus',
    ERR_INVALID_STATUS: 'InvalidStatus',
    ERR_EXCEED_MAX_TENDER_TIME_SETTING: 'ExceedMaxTenderTimeSetting',
    ERR_OFFER_OWN_TENDER: 'OfferOwnTender',
    ERR_MULTI_OFFER_SAME_TENDER: 'MULTI_OFFER_SAME_TENDER',
    ERR_UPDATE_DECIDED_OFFER: 'UPDATE_DECIDED_OFFER'
};