module.exports = {
  log: require('./log'),
  User: require('./user'),
  Brand: require('./brand'),
  Category: require('./category'),
  Company: require('./company'),
  CompanyType: require('./company-type'),
  Faq: require('./faq'),
  IssueReport: require('./issue-report'),
  Offer: require('./offer'),
  Payment: require('./payment'),
  Product: require('./product'),
  Subscription: require('./subscription'),
  Tender: require('./tender'),
  AccessControl: require('./access-control'),
  Aboutus: require('./about-us'),
  ContactInfo: require('./contact-info'),
  PrivacyPolicy: require('./privacy-policy'),
  Terms: require('./terms'),
  Stats: require('./stats'),
  Country: require('./country'),
  City: require('./city'),
  Ads: require('./ads'),
  Reports: require('./reports')
}